#!/bin/bash
node="$(which node)"
pidfile="pm2-gui.pid"
prefixINFO="\033[1;32m[INFO]\033[0m"
prefixWARN="\033[1;33m[WARNING]\033[0m"

function isRunning() {
  if [ ! -f $pidfile ];
    then
      return 0;
  fi
  if [ ! -s $pidfile ];
    then 
      rm $pidfile;
      return 0;
  fi
  if test $(ps -p $(cat $pidfile) | wc -l) -gt 1;
    then 
      return 1;
  fi 
  rm $pidfile;
  return 0;
}

function status() {
  isRunning;
  if [ 0 -eq $? ];
    then
      echo -e "$prefixWARN \033[31m✘ stopped\033[0m";
  else
    echo -e "$prefixINFO \033[32m✔ running\033[0m";
  fi
}

function server (){
  isRunning;
    if [ 0 -eq $? ];
      then
        echo -e "$prefixINFO Starting..."
        $node ./lib/daemon "$@"
        sleep 1;
    fi
    status;
}

function usage () {
  cat <<-EOF

  Usage: $0 <cmd> [options]

  Commands:
    start [config_file]   start the service, including agent and web server
    agent [config_file]   start the agent only
    stop                  stop the running service
    restart               restart the service
    mon                   run the curses-like dashboard in terminal
    status                show the status of service
    logs [log_directory]  view the logs

  Examples:
    $0 start
    $0 start /path/to/my-pm2-gui.ini
    $0 mon
    $0 logs
    $0 logs /path/to/logs

EOF
}

case "$1" in
  start)
    server "$@";
    ;;

  agent)
    server "$@";
    ;;

  stop)
    isRunning;
    if [ 0 -eq $? ];
      then
        echo -e "$prefixWARN Already stopped.";
    else
      echo -e "$prefixINFO Stopping..."
      kill $(cat $pidfile);
      sleep 1;
      status;
    fi
    ;;

  restart)
    isRunning;
    if [ 0 -eq $? ];
      then
        echo -e "$prefixWARN PID not found, no need to stop anything.";
        $node ./lib/daemon "$@"
    else
      kill -SIGHUP $(cat $pidfile);
    fi
    sleep 1;
    status;
    ;;

  logs)
    out="pm2-gui.out";
    err="pm2-gui.err";
    if [ ! -n "$2" ];
      then
        out="./logs/$out";
        err="./logs/$err";
    else
      out="$2/$out";
      err="$2/$err";
    fi
    if [ ! -f $out ] && [ ! -f $err ];
      then
        echo -e "$prefixWARN Logs can not be found in directory \033[1m$2\033[0m.";
    else
      echo -e "$prefixINFO Logs from \033[1m$out\033[0m and \033[1m$err\033[0m:";
      tail -n 20 -F $out $err;
    fi
    ;;

  status)
    status;
    ;;

  *)
    usage "$0";
    exit 1
    ;;
esac